### ISSUE TITLE
only error message displays no information

### ISSUE THREAD

**Issue by lisawebcoder** [aakashpawar1999/word-dictionary#1]
hello sir
thank you for your github code and video
so far after i put my new APi key from wordnik
the application still does not sisplay any info

is it something to do witht he audi code?
i dont think so
but is there some info we have to enter there?

Lisa

**Comment by aakashpawar1999** [comment]
Once you have your API key, you can use it directly. There is nothing more
to do.

**Comment by lisawebcoder** [comment]
thank you for the reply
i got it working
but if i may
i still have a question?
how can get many results?
i get only one result
which paramter do we add or change in the API endpoint plz?
thank you sir
Lisa

**Comment by aakashpawar1999** [comment]
Nice to hear that it's working.
Now the thing is that I have tried and I don't know if you can get multiple
words result but you can try using loop and go through all the words that
you want to get the JSON response for. But with api you can only get one
words response.

You should check the documentation. Maybe they have some way around that.

**Comment by aakashpawar1999** [comment]
I am closing this issue.
